const data={
    foods:[
        {
            id:"1",
            name:"Idly",
            price:10,
            image:"./images/m-1.jpg"
        },
        {
            id:"2",
            name:"Dosa",
            price:20,
            image:"./images/m-2.jpeg"
        },
        {
            id:"3",
            name:"Poori",
            price:25,
            image:"./images/m-3.jpg"
        },
        {
            id:"4",
            name:"Chapathi",
            price:25,
            image:"./images/m-4.jfif"
        },
        {
            id:"5",
            name:"Parotta",
            price:30,
            image:"./images/m-5.jpg"
        },
        {
            id:"6",
            name:"Pongal",
            price:50,
            image:"./images/m-6.jpg"
        },
        {
            id:"7",
            name:"Semiya",
            price:60,
            image:"./images/m-7.jfif"
        },
        {
            id:"8",
            name:"Puttu",
            price:55,
            image:"./images/m-8.jpg"
        },
        {
            id:"9",
            name:"Appam",
            price:40,
            image:"./images/m-9.jpg"
        },
        {
            id:"10",
            name:"Paniyaram",
            price:20,
            image:"./images/m-10.jpg"
        },
        {
            id:"11",
            name:"Biryani",
            price:100,
            image:"./images/m-11.jpg"
        },
        {
            id:"12",
            name:"Curd rice",
            price:50,
            image:"./images/m-12.jpg"
        },
        {
            id:"13",
            name:"tomato Rice",
            price:60,
            image:"./images/m-13.jpg"
        },
        {
            id:"14",
            name:"Omlet",
            price:30,
            image:"./images/m-14.jfif"
        },
        {
            id:"15",
            name:"Lemon rice",
            price:45,
            image:"./images/m-15.jpg"
        },
    ]
}

export default data;